export { default as Login} from './Login'
export { default as Signup} from './Signup'
export { default as PublicUp} from './PublicUp'
export { default as All} from './All'
export { default as Home} from './Home'
export { default as Like} from './Like'
export { default as Roll} from './Roll'
export { default as Mainhome} from './Mainhome'